site_name: Платформа Гамма. Справочник
#site_url: https://gamma-manual.ru/
site_description: Инструкция по использованию ПО Гамма
site_author: ООО "Омни Дата"
use_directory_urls: false
theme:
  name: material
  #name: material
  language: ru
  logo: files/Gamma_Icon_full.png
  favicon: files/Gamma_Icon_full.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: переключить в темный режим
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: переключить в светлый режим

  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.sections
    #- navigation.expand
    - toc.follow
    #- toc.integrate
    # - navigation.indexes
    #- navigation.instant
    #- navigation.instant.prefetch
  

markdown_extensions:
  - fenced_code
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  #- attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



nav:
  - Установка:
    - Содержание: install/index.md
    - Windows: install\windows\index.md
    - Linux:
        - Обновление Python: install\linux\python_update_astra.md
        - install\linux\podman_linux_install.md
        - install\linux\server_install_update.md
        - install\linux\client_astra_install.md
        - install\linux\client_update.md
    - Другое: install\windows\index.md
  - Интерфейс:
    - Содержание: ux/index.md
    - Базовые окна:
      #- ux/basic_widgets/index.md
      - Главное окно: ux\basic_widgets\main_window.md
      - Браузер проектов: ux\basic_widgets\project_browser.md
      - Окно свойств: ux/basic_widgets/properties_window.md
      - Рабочий процесс: ux\basic_widgets\workflow.md
      - Журнал событий: ux\basic_widgets\journal.md
    - Инструменты анализа:
      #- ux/graph_widgets/index.md
      - Планшет: ux\graph_widgets\logview.md
      - Кросс-плот: ux\graph_widgets\сross-plot.md
      - Гистограмма: ux\graph_widgets\histogram.md
      - Таблица: ux\graph_widgets\tableview.md
      - Карта: ux\graph_widgets\map.md
      - Тепловая карта: ux\graph_widgets\heatmap.md

  - Обработка:
    - processing/index.md
  - Интерпретация: interpretation/index.md
  - Python: python/index.md
  #- Другое: other/index.md


#copyright: Все права защищены, ООО "Омни Дата", 2024


extra:
  #consent:
    #description: >- 
      #Мы используем куки для того, чтобы пользоваться сайтом было удобнее.
  analytics:
    provider: google
    property: G-ELG9CKFVZ2
    feedback:
      title: Полезная страница?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, очень полезно!
          data: 1
          note: >-
            Рады, что вам понравилось!
        - icon: material/emoticon-sad-outline
          name: Нужно еще поработать над содержимым страницы...
          data: 0
          note: >-
            Спасибо за ваше мнение. Мы подумаем как сделать лучше.
