site_name: ПО Гамма
theme: 
  name: material
  language: ru
  logo: imgs/Gamma_Icon_full.png
  favicon: imgs/Gamma_Icon_full.png
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    #- navigation.tabs
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.indexes


